sonar.projectKey=ges.the-vision
sonar.projectName=The Vision
sonar.projectVersion=1.0
sonar.sources=.
sonar.sourceEncoding=UTF-8

sonar.exclusions=**/*.m,**/*.mlapp,**/*.mwapp,**/node_modules/**,**/dist/**,**/build/**,**/.venv/**,**/venv/**,**/__pycache__/**,**/Assets/processed/**,**/assets/processed/**,**/logs/**,**/*.min.js,**/*.bundle.js,**/.next/**,**/target/**,**/Pods/**,**/DerivedData/**,**/coverage/**,**/.git/**,**/_archive/**

sonar.host.url=http://localhost:9000
